<?php

return [

    /*
    |--------------------------------------------------------------------------
    | API Prefix
    |--------------------------------------------------------------------------
    |
    | The URL prefix for all API routes generated by the plugin.
    | Default: 'api/v1'
    |
    */
    'api_prefix' => env('API_FORGE_PREFIX', 'api/v1'),

    /*
    |--------------------------------------------------------------------------
    | API Version
    |--------------------------------------------------------------------------
    |
    | The current API version. Used in route generation and documentation.
    |
    */
    'api_version' => env('API_FORGE_VERSION', 'v1'),

    /*
    |--------------------------------------------------------------------------
    | Rate Limiting
    |--------------------------------------------------------------------------
    |
    | Maximum number of API requests per minute per token.
    |
    */
    'rate_limit' => env('API_FORGE_RATE_LIMIT', 60),

    /*
    |--------------------------------------------------------------------------
    | Pagination
    |--------------------------------------------------------------------------
    |
    | Default and maximum items per page for list endpoints.
    |
    */
    'pagination' => [
        'default_per_page' => 15,
        'max_per_page' => 100,
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication
    |--------------------------------------------------------------------------
    |
    | Configure API authentication settings.
    |
    */
    'auth' => [
        'enabled' => true,
        'default_expiration_days' => 365,

        // Issue forge_refresh_ tokens alongside access tokens. Refresh tokens
        // can be exchanged for a new access token at POST auth/token/refresh
        // even after the access token has expired.
        'refresh_tokens' => env('API_FORGE_REFRESH_TOKENS', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Documentation
    |--------------------------------------------------------------------------
    |
    | Configure the auto-generated API documentation.
    |
    */
    'docs' => [
        'enabled' => true,
        'path' => 'api-docs',
        'title' => 'API Documentation',
        'description' => 'Auto-generated API documentation for Filament resources.',
        'theme' => 'dark', // 'dark' or 'light'
    ],

    /*
    |--------------------------------------------------------------------------
    | Resource Discovery
    |--------------------------------------------------------------------------
    |
    | Control how the plugin discovers and exposes Filament resources.
    |
    */
    'discovery' => [
        // Only resources implementing HasApi interface will be exposed
        'auto_discover' => true,

        // Allowed HTTP methods for API endpoints
        'allowed_methods' => ['index', 'show', 'store', 'update', 'destroy'],

        // Global middleware applied to all API routes
        'middleware' => [
            'api',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Query Builder
    |--------------------------------------------------------------------------
    |
    | Configure Spatie Query Builder defaults.
    |
    */
    'query_builder' => [
        'enable_filters' => true,
        'enable_sorts' => true,
        'enable_includes' => true,
        'enable_fields' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Events & Hooks
    |--------------------------------------------------------------------------
    |
    | Configure the event/hook system for API lifecycle events.
    |
    */
    'events' => [
        'enabled' => true,
        'dispatch_events' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | File Uploads
    |--------------------------------------------------------------------------
    |
    | Configure file upload handling for API endpoints.
    |
    */
    'uploads' => [
        'default_disk' => env('API_FORGE_UPLOAD_DISK', 'public'),
        'max_file_size' => 10240, // KB
    ],

    /*
    |--------------------------------------------------------------------------
    | Custom Actions
    |--------------------------------------------------------------------------
    |
    | Configure custom action endpoint settings.
    |
    */
    'actions' => [
        'prefix' => 'actions',
    ],

    /*
    |--------------------------------------------------------------------------
    | Nested Resources
    |--------------------------------------------------------------------------
    |
    | Configure nested resource endpoint settings.
    |
    */
    'nested_resources' => [
        'enabled' => true,
        'max_nesting_depth' => 1,
    ],

    /*
    |--------------------------------------------------------------------------
    | Batch Operations
    |--------------------------------------------------------------------------
    |
    | Configure batch/bulk operation settings.
    |
    */
    'batch' => [
        'enabled' => true,
        'max_size' => 100,
        'allowed_operations' => ['create', 'update', 'delete'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Export
    |--------------------------------------------------------------------------
    |
    | GET {resource}/export?format=csv|json — requires 'export' in the
    | resource's allowed_methods.
    |
    */
    'export' => [
        'enabled'  => true,
        'max_rows' => 10000,
        'formats'  => ['csv', 'json'],
    ],

    /*
    |--------------------------------------------------------------------------
    | Audit Log
    |--------------------------------------------------------------------------
    |
    | Log every API request (token, action, status, duration, IP) to the
    | api_forge_request_logs table. Prune with: php artisan api-forge:prune-logs
    |
    */
    'audit' => [
        'enabled'    => env('API_FORGE_AUDIT', true),
        'prune_days' => 30,
    ],

    /*
    |--------------------------------------------------------------------------
    | Notifications
    |--------------------------------------------------------------------------
    |
    | Token expiry warnings sent by: php artisan api-forge:notify-expiring
    |
    */
    'notifications' => [
        'channels'    => ['mail', 'database'],
        'expiry_days' => 7,
    ],

    /*
    |--------------------------------------------------------------------------
    | Response Cache
    |--------------------------------------------------------------------------
    |
    | Cache GET index/show responses. Any write to a resource (including
    | batch, nested and custom actions) invalidates its cached responses.
    |
    */
    'cache' => [
        'enabled' => env('API_FORGE_CACHE', false),
        'ttl'     => 60,   // seconds
        'store'   => null, // null = default cache store
    ],

    /*
    |--------------------------------------------------------------------------
    | Webhooks
    |--------------------------------------------------------------------------
    |
    | HTTP callbacks fired on API write events. Manage endpoints in the
    | api_forge_webhooks table; payloads are signed with X-ApiForge-Signature
    | when the webhook has a secret.
    |
    */
    'webhooks' => [
        'enabled' => true,
        'timeout' => 10, // seconds
    ],

    /*
    |--------------------------------------------------------------------------
    | Multi-Tenancy
    |--------------------------------------------------------------------------
    |
    | When a token carries a tenant_id and a resource declares
    | apiConfig()['tenant_column'], every query is scoped to that tenant
    | and created records are stamped with it.
    |
    */
    'multi_tenant' => [
        'enabled' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | API Versions
    |--------------------------------------------------------------------------
    |
    | null  → single-version mode using 'api_prefix' (default).
    | array → multi-version mode, e.g. ['v1', 'v2']: routes are registered
    |         under {api_base}/{version} for each entry, and resources can
    |         opt into specific versions with #[ApiVersion('v2')].
    |
    */
    'versions' => null,
    'api_base' => env('API_FORGE_BASE', 'api'),

    /*
    |--------------------------------------------------------------------------
    | GraphQL
    |--------------------------------------------------------------------------
    |
    | Optional GraphQL endpoint (POST {api_prefix}/graphql) with a schema
    | generated from your HasApi resources. Requires webonyx/graphql-php.
    |
    */
    'graphql' => [
        'enabled' => env('API_FORGE_GRAPHQL', false),
    ],

    /*
    |--------------------------------------------------------------------------
    | Navigation
    |--------------------------------------------------------------------------
    |
    | Configure how the plugin appears in the Filament panel navigation.
    |
    */
    /*
    |--------------------------------------------------------------------------
    | Route Segment
    |--------------------------------------------------------------------------
    |
    | The URL segment used in API paths instead of the panel ID.
    | Example: 'filament' → GET /api/v1/filament/posts
    | Leave null to use the panel ID (default behavior).
    |
    */
    'route_segment' => env('API_FORGE_ROUTE_SEGMENT', null),

    'navigation' => [
        'group' => 'Developer Center',
        'icon' => 'heroicon-o-code-bracket-square',
        'sort' => 100,
    ],

];
