<?php

return [

    /*
    |--------------------------------------------------------------------------
    | API Prefix
    |--------------------------------------------------------------------------
    |
    | The URL prefix for all API routes generated by the plugin.
    | Default: 'api/v1'
    |
    */
    'api_prefix' => env('API_FORGE_PREFIX', 'api/v1'),

    /*
    |--------------------------------------------------------------------------
    | API Version
    |--------------------------------------------------------------------------
    |
    | The current API version. Used in route generation and documentation.
    |
    */
    'api_version' => env('API_FORGE_VERSION', 'v1'),

    /*
    |--------------------------------------------------------------------------
    | Rate Limiting
    |--------------------------------------------------------------------------
    |
    | Maximum number of API requests per minute per token.
    |
    */
    'rate_limit' => env('API_FORGE_RATE_LIMIT', 60),

    /*
    |--------------------------------------------------------------------------
    | Pagination
    |--------------------------------------------------------------------------
    |
    | Default and maximum items per page for list endpoints.
    |
    */
    'pagination' => [
        'default_per_page' => 15,
        'max_per_page' => 100,
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication
    |--------------------------------------------------------------------------
    |
    | Configure API authentication settings.
    |
    */
    'auth' => [
        'enabled' => true,
        'default_expiration_days' => 365,
    ],

    /*
    |--------------------------------------------------------------------------
    | Documentation
    |--------------------------------------------------------------------------
    |
    | Configure the auto-generated API documentation.
    |
    */
    'docs' => [
        'enabled' => true,
        'path' => 'api-docs',
        'title' => 'API Documentation',
        'description' => 'Auto-generated API documentation for Filament resources.',
        'theme' => 'dark', // 'dark' or 'light'
    ],

    /*
    |--------------------------------------------------------------------------
    | Resource Discovery
    |--------------------------------------------------------------------------
    |
    | Control how the plugin discovers and exposes Filament resources.
    |
    */
    'discovery' => [
        // Only resources implementing HasApi interface will be exposed
        'auto_discover' => true,

        // Allowed HTTP methods for API endpoints
        'allowed_methods' => ['index', 'show', 'store', 'update', 'destroy'],

        // Global middleware applied to all API routes
        'middleware' => [
            'api',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Query Builder
    |--------------------------------------------------------------------------
    |
    | Configure Spatie Query Builder defaults.
    |
    */
    'query_builder' => [
        'enable_filters' => true,
        'enable_sorts' => true,
        'enable_includes' => true,
        'enable_fields' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Navigation
    |--------------------------------------------------------------------------
    |
    | Configure how the plugin appears in the Filament panel navigation.
    |
    */
    /*
    |--------------------------------------------------------------------------
    | Route Segment
    |--------------------------------------------------------------------------
    |
    | The URL segment used in API paths instead of the panel ID.
    | Example: 'filament' → GET /api/v1/filament/posts
    | Leave null to use the panel ID (default behavior).
    |
    */
    'route_segment' => env('API_FORGE_ROUTE_SEGMENT', null),

    'navigation' => [
        'group' => 'Developer Center',
        'icon' => 'heroicon-o-code-bracket-square',
        'sort' => 100,
    ],

];
